# Generated by Django 3.0 on 2020-05-24 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloaded_movies',
            fields=[
                ('download_by', models.CharField(max_length=100)),
                ('downloaded_on', models.DateTimeField(verbose_name='downloaded on')),
                ('title_long', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('yify_id', models.CharField(max_length=20)),
                ('imdb_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('genres', models.TextField()),
                ('rating', models.IntegerField()),
                ('description_intro', models.TextField()),
                ('yt_trailer_code', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=20)),
                ('runtime', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Yify Movies',
            },
        ),
        migrations.CreateModel(
            name='Downloading',
            fields=[
                ('download_by', models.CharField(max_length=100)),
                ('downloaded_on', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 15, 59, 14, 839645))),
                ('title_long', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('yify_id', models.CharField(max_length=20)),
                ('imdb_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('genres', models.TextField()),
                ('rating', models.IntegerField()),
                ('description_intro', models.TextField()),
                ('yt_trailer_code', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=20)),
                ('runtime', models.IntegerField()),
                ('progress', models.CharField(max_length=10)),
                ('downloading', models.BooleanField()),
                ('img_url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Downloading',
            },
        ),
    ]
