# Generated by Django 3.0 on 2020-05-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yify', '0002_auto_20200524_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('ip', models.TextField()),
                ('title_long', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 17, 41, 28, 382609))),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
        migrations.AlterField(
            model_name='downloading',
            name='downloaded_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 17, 41, 28, 382218)),
        ),
    ]
